# Generated by Django 3.0.3 on 2020-02-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalas',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='kalas',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
