# Generated by Django 3.0.3 on 2020-02-27 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200227_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kalas',
            name='zipCode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='names',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='user.Kalas'),
        ),
    ]
