# Generated by Django 3.0.3 on 2020-02-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200227_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='names',
            old_name='userID',
            new_name='kalasID',
        ),
    ]
