# Generated by Django 3.0.3 on 2020-03-11 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200227_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foresporsel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='merge med oss', max_length=200)),
                ('kalasReciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciver', to='user.Kalas')),
                ('kalasSender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='user.Kalas')),
            ],
        ),
    ]
