# Generated by Django 3.0.3 on 2020-03-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_foresporsel'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalas',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='kalas_pictures'),
        ),
    ]
