# Generated by Django 3.0.3 on 2020-03-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_kalas_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kalas',
            name='picture',
        ),
    ]
