# Generated by Django 3.0.3 on 2020-03-19 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_borst'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borst',
            old_name='question',
            new_name='text',
        ),
    ]
