# Generated by Django 3.0.3 on 2020-03-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200319_1734'),
        ('user', '0008_remove_kalas_picture'),
    ]

    operations = [
    ]
